eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://127.0.0.1:8761/eureka}
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true

server:
  port: 8070
spring:
  application:
    name: schools
  zipkin:
      baseUrl: http://127.0.0.1:9411/

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schools
    username: postgres
    password: root123
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    students-url: http://localhost:8090/api/v1/students

management:
  tracing:
    sampling:
      probability: 1.0