server:
  port: 8761

spring:
  config:
    import: optional:configserver:http://localhost:8761/
  application:
    name: discovery
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false